name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew -v
      - run: ./gradlew check
      - run: ./gradlew build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build/distributions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}